// flow-typed signature: 0b041b8b673044d585978c135822687e
// flow-typed version: <<STUB>>/@4c/babel-preset_v^5.2.0/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@4c/babel-preset'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@4c/babel-preset' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@4c/babel-preset/intl-preset' {
  declare module.exports: any;
}

declare module '@4c/babel-preset/namespace-plugin' {
  declare module.exports: any;
}

declare module '@4c/babel-preset/test/plugin.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@4c/babel-preset/index' {
  declare module.exports: $Exports<'@4c/babel-preset'>;
}
declare module '@4c/babel-preset/index.js' {
  declare module.exports: $Exports<'@4c/babel-preset'>;
}
declare module '@4c/babel-preset/intl-preset.js' {
  declare module.exports: $Exports<'@4c/babel-preset/intl-preset'>;
}
declare module '@4c/babel-preset/namespace-plugin.js' {
  declare module.exports: $Exports<'@4c/babel-preset/namespace-plugin'>;
}
declare module '@4c/babel-preset/test/plugin.test.js' {
  declare module.exports: $Exports<'@4c/babel-preset/test/plugin.test'>;
}
